/**
 * The documentation shell — development only.
 *
 * Every page under here renders data produced by `backend/scripts/generate_docs.py`, or fetched
 * live from the running API. Nothing on these pages is typed out by hand twice: documentation that
 * is a copy of a source of truth goes stale, and stale documentation is worse than none because it
 * is believed.
 *
 * The whole tree is behind `DOCS_ENABLED` (see `lib/docs.ts`), which folds to a literal at build
 * time, so a build without it contains neither the routes nor this code.
 */

import { NavLink, Outlet } from "react-router-dom";

import { PageHeading } from "../../components/Layout";
import { cx } from "../../lib/cx";
import meta from "../../docs/generated/meta.json";

const PAGES = [
  { to: "/docs/requirements", label: "Requirements" },
  { to: "/docs/endpoints", label: "API" },
  { to: "/docs/architecture", label: "Architecture" },
  { to: "/docs/features", label: "Features" },
  { to: "/docs/tests", label: "Tests" },
];

export function DocsLayout() {
  return (
    <>
      <PageHeading title="Documentation" />

      <div className="mb-5 flex flex-wrap gap-1 border-b border-rule">
        {PAGES.map((page) => (
          <NavLink
            key={page.to}
            to={page.to}
            className={({ isActive }) =>
              cx(
                "-mb-px border-b-2 px-3 py-2 text-[13px]",
                isActive
                  ? "border-accent font-medium text-ink"
                  : "border-transparent text-ink-muted hover:text-ink",
              )
            }
          >
            {page.label}
          </NavLink>
        ))}
      </div>

      <Outlet />

      <p className="mt-8 border-t border-rule pt-4 text-[12px] text-ink-muted">
        Generated by <span className="font-mono">{meta.generated_by}</span> · API v
        {meta.api_version} · {meta.endpoint_count} endpoints verified. Run{" "}
        <span className="font-mono">make docs</span> to regenerate,{" "}
        <span className="font-mono">make docs-check</span> to fail on drift. This section is not
        included in production builds.
      </p>
    </>
  );
}
